---
swagger: "2.0"
info:
  version: "1.2"
  title: "Sink DC API"
host: "example.sink.example"
basePath: "/api/1.2/dc"
paths:
  /user/{user_id}/consentRecord/{cr_id}/resourceSet/{rs_id}:
    get:
      tags:
      - "Sink"
      description: "End point that initializes data connection flow "
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "user_id"
        description: "Unique id for useraccount in sink"
        required: true
        type: string
      - in: "path"
        name: "cr_id"
        description: "Existing consentrecord id"
        required: true
        type: string
      - in: "path"
        name: "rs_id"
        description: "Resource set id"
        required: true
        type: string
      - in: "query"
        name: "data_set_id"
        description: "Dataset id"
        required: false
        type: string
      responses:
        202:
          description: "Returns "
          schema:
            $ref: "#/definitions/processing"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/errors"

  /status/{process_id}:
    get:
      tags:
      - "Sink"
      description: "Query status of on going data flow"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "process_id"
        description: "Unique id for background process."
        required: true
        type: string
      responses:
        200:
          description: "Returns status of processing "
          schema:
            $ref: "#/definitions/handling"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/errors"

definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI
  processing:
      type: object
      properties:
        process_id:
          type: string
          description: Id that can be used to query status of processing
  handling:
      type: object
      properties:
        status:
          type: string
          description: Status of process (Active/Done/Cancelled)
        reason:
          type: string
          description: Verbal description for status
