---
swagger: "2.0"
info:
  version: "1.3"
  title: "Service Management SLR API"
host: "example.service_mgmnt.example"
basePath: "/api/1.3/slr"
paths:
  /linking:
    post:
      tags:
      - "Service Linking"
      description: "Begins Service Linking process with Operator"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Information required to start linking process with the operator"
        required: true
        schema:
          $red: "#/definitions/StartLinkingParams"
      responses:
        201:
          description: "Returns 201 Created containing created Service Link"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"

  /surrogate_id:
    post:
      tags:
      - "Service Linking"
      description: "Called to generate a surrogate_id between Operator and a Service"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Operator_id and user_id."
        required: true
        schema:
          $ref: "#/definitions/GenSurrogateParams"
      responses:
        201:
          description: "Returns 201 CREATED with generated surrogate_id"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"

  /slr:
    post:
      tags:
      - "Service Management"
      - "Operator"
      description: "Takes SLR signed by account owner at Operator, signs it with own key and sends\
        \ to Operator for verification."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "code and user_id, here user_id is mandatory."
        required: true
        schema:
          $ref: "#/definitions/SlrParams"
      responses:
        200:
          description: "Returns 200 OK"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI

  GenSurrogateParams:
    type: "object"
    properties:
      operator_id:
        type: "string"
        description: "string containing operator_id"
      user_id:
        type: "string"
        description: "string containing user_id."

  StartLinkingParams:
    type: "object"
    properties:
      operator_id:
        type: "string"
        description: "string containing operator_id"
      code:
        type: "string"
        description: "string containing code."
      surrogate_id:
        type: "string"
        description: "string containing surrogate_id."
      return_url:
        type: "string"
        description: "string containing return_url."


  SlrParams:
    type: "object"
    properties:
      data:
        type: object
        properties:
          code:
            type: string
            description: string containing code
      slr:
        type: object
        description: "See: https://github.com/HIIT/mydata-stack/raw/gh-pages/mydata-service-linking.pdf"
