---
swagger: "2.0"
info:
  version: "1.2.1"
  title: "Service Management SLR API"
host: "example.service_mgmnt.example"
basePath: "/api/1.2/slr"
paths:
  /auth:
    post:
      tags:
      - "Service Management"
      - "Service"
      description: "Service calls this after user has authenticated. Causes Service\
        \ Management to generate surrogate_id for the operator. This endpoint starts a long chain of events."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "code and user_id."
        required: true
        schema:
          $ref: "#/definitions/LoginParams"
      responses:
        200:
          description: "Returns 200 OK so Service Mngmt knows SLR was verified\
            \ successfully"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"

  /slr:
    post:
      tags:
      - "Service Management"
      - "Operator"
      description: "Takes SLR signed by account owner at Operator, signs it with own key and sends\
        \ to Operator for verification."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "code and user_id, here user_id is mandatory."
        required: true
        schema:
          $ref: "#/definitions/SlrParams"
      responses:
        200:
          description: "Returns 200 OK"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI

  LoginParams:
    type: "object"
    properties:
      code:
        type: "string"
        description: "string containing code"
      user_id:
        type: "string"
        description: "string containing user_id."
  SlrParams:
    type: "object"
    properties:
      data:
        type: object
        properties:
          code:
            type: string
            description: string containing code
      slr:
        type: object
        description: "See: https://github.com/HIIT/mydata-stack/raw/gh-pages/mydata-service-linking.pdf"
