---
swagger: "2.0"
info:
  version: "1.3"
  title: "Operator SLR API"
host: "example.operator.example"
basePath: "/api/1.2/slr"

securityDefinitions:
  BasicAuth:
    type: basic
    description: HTTP Basic Auth

  apiKeyUser:
    type: apiKey
    name: "Api-Key-User"
    description: "Defines user that is performing operations. Possible user's are MyData Account Owner's"
    in: header

paths:
  /account/{account_id}/service/{service_id}:
    get:
      security:
        - apiKeyUser: []
      tags:
      - "Operator External - SLR"
      description: "Entrypoint for creating new SLR with service.\nWill take UUID\
        \ of service to link with as paramater. Returns redirect to Service Login. This endpoint will start chain of events."
      parameters:
      - name: "account_id"
        in: "path"
        description: "Unique ID of user initiating process."
        required: true
        type: "string"
        format: "uuid4"
      - name: "service_id"
        in: "path"
        description: "Unique ID of service to make SLR with."
        required: true
        type: "string"
        format: "uuid4"
      responses:
        302:
          description: "Returns Redirect to Service Login page for authentication."
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        504:
          description: "Gateway Timeout"
          schema:
            $ref: "#/definitions/errors"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /account/{account_id}/service/{service_id}/slr/{link_id}:
    delete:
      security:
        - apiKeyUser: []
      tags:
      - "Operator External - SLR"
      description: "Endpoint for Disabling Active SLR."
      parameters:
      - name: "account_id"
        in: "path"
        description: "Unique ID of user initiating process."
        required: true
        type: "string"
        format: "uuid4"
      - name: "service_id"
        in: "path"
        description: "Unique ID of service to make SLR with."
        required: true
        type: "string"
        format: "uuid4"
      - name: "link_id"
        in: "path"
        description: "Unique ID of Service Link"
        required: true
        type: "string"
        format: "uuid4"
      responses:
        200:
          description: "Returns Created SSR signifying the status change to Disabled."
          schema:
            $ref: "#/definitions/SSR"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        504:
          description: "Gateway Timeout"
          schema:
            $ref: "#/definitions/errors"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"


  /link:
    post:
      tags:
      - "Operator Internal - SLR"
      description: "End point where Service Mgmnt POSTs after user has been authenticated\
        \ by the Service inorder to deliver surrogate id to Operator."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contains code, surrogate_id and incase of Sink service a token_key"
        required: true
        schema:
          $ref: "#/definitions/LinkParams"
      responses:
        201:
          description: "Returns 201 CREATED and the created SLR"
          schema:
            $ref: "#/definitions/VerifyResponse"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /verify:
    post:
      tags:
      - "Operator Internal - SLR"
      description: "End point where Service Mgmnt POSTs after signing SLR from Operator"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "slr and ssr"
        required: true
        schema:
          $ref: "#/definitions/VerifyParams"
      responses:
        201:
          description: "Returns 201 CREATED so Service Mngmt knows SLR was verified\
            \ successfully"
          schema:
            $ref: "#/definitions/VerifyResponse"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"
definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI

  SLR_content:
   type: "object"
   properties:
    attributes:
      type: "object"
      properties:
        protected:
          type: "string"
        payload:
          type: "string"
        signatures:
          type: array
          items:
            type: object
    type:
      type: "string"
    id:
      type: "string"

  SSR_content:
   type: "object"
   properties:
    attributes:
      type: "object"
      properties:
        header:
          type: "object"
        protected:
          type: "string"
        payload:
          type: "string"
        signature:
          type: "string"
    type:
      type: "string"
    id:
      type: "string"

  SSR:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/SSR_content"


  LinkParams:
    type: "object"
    properties:
      code:
        type: "string"
        description: "string containing code"
      token_key:
        $ref: "#/definitions/LinkParams_token_key"
      surrogate_id:
        type: "string"
        description: "string containing surrogate_id"

  VerifyParams:
    type: "object"
    properties:
      data:
        type: object
        properties:
          code:
            type: string
            description: string containing code
      slr:
        type: object
        properties:
          signatures:
            type: array
            items:
              type: string
          payload:
            type: string
            description: string containing payload
  LinkParams_token_key:
    properties:
      kty:
        type: "string"
        description: "string containing kty"
      x:
        type: "string"
        description: "string containing x"
      kid:
        type: "string"
        description: "string containing kid"
      crv:
        type: "string"
        description: "string containing crv"
      y:
        type: "string"
        description: "string containing y"

  VerifyResponse:
    type: object
    properties:
      code:
        type: string
        description: string containing code
      data:
        type: object
        properties:
          ssr:
            $ref: "#/definitions/SSR_content"
          slr:
            $ref: "#/definitions/SLR_content"


